// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Links from "../api/links";
import * as ReactMeteorData from "meteor/react-meteor-data";

var linksCollection = Links.LinksCollection;

function Info$Info(Props) {
  var links = (ReactMeteorData.useTracker(() => linksCollection.find().fetch()));
  var items = Belt_Array.map(links, (function (link) {
          return React.createElement("li", {
                      key: link._id
                    }, React.createElement("a", {
                          href: link.url,
                          target: "_blank"
                        }, link.title));
        }));
  return React.createElement("div", undefined, React.createElement("h2", undefined, "Learn Meteor!"), React.createElement("ul", undefined, items));
}

var Info = {
  make: Info$Info
};

export {
  linksCollection ,
  Info ,
}
/* linksCollection Not a pure module */
